name: render readme

# Controls when the action will run
on:
  push:
    branches: master
  schedule:
  - cron: 0 */4 * * *

jobs:
  render:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: r-lib/actions/setup-r@v1
      # - uses: r-lib/actions/setup-r-dependencies@v1
      # - uses: r-lib/actions/setup-pandoc@v1
      # - name: Install packages
      #   run: Rscript -e 'install.packages("rmarkdown", "pacman")'
      # - name: Render README
      #   run: Rscript -e 'rmarkdown::render("README.Rmd", output_format = "md_document")'
      # - name: Commit results
      #   ena
      #   run: |
      #     git add README.md man/figures/README-*
      #     git commit README.md -am 'Re-build README.md' || echo "No changes to commit"
      #     git push origin master || echo "No changes to commit"