on:
  push:
    paths:
      - README.Rmd
  schedule:
  - cron: 0 */4 * * *

name: Render README 2

jobs:
  render:
    name: Render README
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2